### ISSUE TITLE
Creating a mesh with markers

### ISSUE THREAD

**Issue by dlorod55** [KVSlab/turtleFSI#101]
Im having trouble creating a mesh

 'get_mesh_domain_and_boundaries
The function is essential and unique for every problem, and has to be provided for the problem file to run. Here you read or define your mesh, domain markers, and boundary markers. In turtle_demo.py we read the mesh data from pre-existing “.xdmf” mesh files. In contrast to defining the domain and boundary markers using FEniCS functions, like in the the ‘Turek flag’-example (TF_fsi.py).

pygmsh and meshio are relevant tools to create geometries. For any question regarding meshing, we refer to the FEniCS documentation and [discourse group](https://fenicsproject.discourse.group/).'

I want to create a simple circle and to visualise and calculate the lift drag and etc when air passes it

**Comment by keiyamamo** [comment]
Hi @dlorod55,

I provided you a mesh with circle previously https://github.com/KVSlab/turtleFSI/issues/91#issuecomment-1756163458, which has circle in the domain. Without any detail or figure of what you mean by “simple circle”, it is hard to help you. 

Note that `turtleFSI` is a general tool for performing FSI simulations and does not contain meshing functionality. Therefore, we can’t support you creating a mesh from scratch. 

Also please kindly advise you to read https://fenicsproject.discourse.group/t/read-before-posting-how-do-i-get-my-question-answered/21 on how to get my question answered  from FEniCS discourse page. This is a good reference point to format question regardless what software you’re using. 

Best,
Kei

**Comment by keiyamamo** [comment]
Closing. Please feel free to reopen @dlorod55
