### ISSUE TITLE
Rotating a flap around a point on a aerofoil every timestamp

### ISSUE THREAD

**Issue by dlorod55** [KVSlab/turtleFSI#104]
Hi,
now successfully made the mesh for aerofoil and positioned the flap on the point where it should hinge. Now i want the flap to rotate about the hinge for every timestamp. But I incorporated it but it remaining the same. My flap angle is changing but mesh isnt rotating.
i put it from -20 to 160 degreed as that when it will be parallel to the aerofoil. Below is the image when andle is -20. so when its 160 it would have rotated 180 degrees anticlockwise.
<img width="481" alt="image" src="https://github.com/KVSlab/turtleFSI/assets/67803167/8bb1168f-4f8d-451e-91a1-efe6d009d826">

heres my code:

# File under GNU GPL (v3) licence, see LICENSE file for details.
# This software is distributed WITHOUT ANY WARRANTY; without even
# the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
# PURPOSE.

"""
[1] Turek, Stefan, and Jaroslav Hron. "Proposal for numerical benchmarking of fluid-structure interaction
between an elastic object and laminar incompressible flow." Fluid-structure interaction.
Springer, Berlin, Heidelberg, 2006. 371-385."""
import mshr
from dolfin import *
import numpy as np
from os import path

from turtleFSI.problems import *
from turtleFSI.modules import *

def set_problem_parameters(default_variables, **namespace):
    # Overwrite or add new variables to 'default_variables'
    default_variables.update(dict(
        # Temporal variables
        T=0.5,                     # End time [s]
        dt=0.01,                  # Time step [s]
        theta=0.5,                # Temporal scheme

        # Physical constants
        Um=1.0,                       # Max. velocity inlet, CDF3: 2.0 [m/s]
        rho_f=1.0e3,                  # Fluid density [kg/m3]
        mu_f=1.0,                     # Fluid dynamic viscosity [Pa.s]
        rho_s=1.0e3,                  # Solid density[kg/m3]
        nu_s=0.4,                     # Solid Poisson ratio [-]
        mu_s=2.0e6,                   # Shear modulus, CSM3: 0.5E6 [Pa]
        lambda_s=4e6,                 # Solid 1st Lame Coefficient [Pa]

        # Problem specific
        folder="ellipse_results",# Name of the results folder
        fluid="fluid",
        solid="no_solid",         # Do not solve for the solid
        extrapolation="no_extrapolation",  # No displacement to extrapolate
        current_flap_angle = -20,
        H=0.8,                        # Total height
        L=2.2,                        # Length of domain, adjusted to fit airfoil
        airfoil_chord_length=0.1,     # Chord length of the airfoil, adjust as needed
        airfoil_position=(0.6, 0.4),  # Position of the airfoil within the domain, adjust as needed
    ))

    return default_variables

def rotate_point(point, angle_deg, rotation_center=(0, 0)):
    """Rotate a point counterclockwise by a given angle around a rotation center."""
    angle_rad = np.radians(angle_deg)
    ox, oy = rotation_center
    px, py = point

    qx = ox + np.cos(angle_rad) * (px - ox) - np.sin(angle_rad) * (py - oy)
    qy = oy + np.sin(angle_rad) * (px - ox) + np.cos(angle_rad) * (py - oy)

    return qx, qy

def rotate_shape(points, angle_deg, rotation_center):
    """Rotate a shape counterclockwise by a given angle around a rotation center."""
    rotated_points = [rotate_point(pt, angle_deg, rotation_center) for pt in points]
    return rotated_points
  
def generate_airfoil(chord_length, num_points=100, angle_of_attack=-20, translate_x=0.2, translate_y=0.5):
    """Generate NACA 0012 airfoil points and translate them."""
    m, p, t = 0, 0, 0.12  # NACA 0012 parameters
    x = np.linspace(0, 1, num_points)
    yt = 5 * t * (0.2969 * np.sqrt(x) - 0.1260 * x - 0.3516 * x**2 + 0.2843 * x**3 - 0.1015 * x**4)

    airfoil_points = [(xi, yi) for xi, yi in zip(x, yt)] + [(xi, -yi) for xi, yi in zip(reversed(x), reversed(yt))]
    
    # Rotate airfoil
    rotated_airfoil_points = [rotate_point(pt, angle_of_attack) for pt in airfoil_points]
    
    # Translate airfoil
    translated_airfoil_points = [(x + translate_x, y + translate_y) for x, y in rotated_airfoil_points]

    return translated_airfoil_points

def sort_points_counter_clockwise(points):
    if not points:
        # Handle empty points array
        return []

    # Compute centroid of the points
    points_array = np.array(points)
    if points_array.ndim != 2 or points_array.shape[1] != 2:
        # Handle incorrect points structure
        raise ValueError("Points array is incorrectly structured.")

    centroid = np.mean(points_array, axis=0)
    cx, cy = centroid

    # Sort points based on the angle from the centroid
    sorted_points = sorted(points, key=lambda point: np.arctan2(point[1] - cy, point[0] - cx))

    return sorted_points
  
def create_rectangular_flap(airfoil_points, flap_width, flap_length_ratio, position_ratio, vertical_offset):
    chord_length = max(pt[0] for pt in airfoil_points) - min(pt[0] for pt in airfoil_points)
    flap_length = chord_length * flap_length_ratio
    flap_start_x = chord_length * position_ratio + min(pt[0] for pt in airfoil_points)

    # Define the four corners of the flap rectangle
    bottom_left = (flap_start_x, -flap_width / 2 + vertical_offset)
    bottom_right = (flap_start_x + flap_length, -flap_width / 2 + vertical_offset)
    top_right = (flap_start_x + flap_length, flap_width / 2 + vertical_offset)
    top_left = (flap_start_x, flap_width / 2 + vertical_offset)

    return [bottom_left, bottom_right, top_right, top_left]

def near_boundary(point, boundary_points, tolerance=0.005):
    """
    Check if a point is near the given set of boundary points.
    """
    return any(np.linalg.norm(np.array(point) - np.array(boundary_point)) < tolerance for boundary_point in boundary_points)

class AirfoilBoundary(SubDomain):
    def __init__(self, sorted_main_airfoil_points, tolerance=0.005):
        super().__init__()
        self.sorted_main_airfoil_points = sorted_main_airfoil_points
        self.tolerance = tolerance

    def inside(self, x, on_boundary):
        return on_boundary and near_boundary(x, self.sorted_main_airfoil_points, self.tolerance)

class FlapBoundary(SubDomain):
    def __init__(self, sorted_flap_points,sorted_main_airfoil_points, tolerance=0.005):
        super().__init__()
        self.sorted_flap_points = sorted_flap_points
        self.sorted_main_airfoil_points = sorted_main_airfoil_points
        self.tolerance = tolerance

    def inside(self, x, on_boundary):
        is_on_flap = near_boundary(x, self.sorted_flap_points, self.tolerance)
        is_not_on_airfoil = not near_boundary(x, self.sorted_main_airfoil_points, self.tolerance)
        return on_boundary and is_on_flap and is_not_on_airfoil
      
**def update_flap_angle(current_angle, min_angle=-20, max_angle=160, step=1):
    """
    Update the flap angle within a specified range.

    Parameters:
    - current_angle: The current angle of the flap.
    - min_angle: The minimum angle limit.
    - max_angle: The maximum angle limit.
    - step: The step size for the angle update.

    Returns:
    - The updated angle.
    """
    # Increment or decrement the angle based on its current value
    if current_angle >= max_angle or current_angle < min_angle:
        step *= -1  # Change direction at extremes

    new_angle = current_angle + step

    # Ensure the new angle stays within the bounds
    if new_angle > max_angle:
        new_angle = max_angle
    elif new_angle < min_angle:
        new_angle = min_angle

    return new_angle**
  

def get_mesh_domain_and_boundaries(L,H,**current_flap_angle**,**namespace):
    channel = mshr.Rectangle(Point(0.0, 0.0), Point(L, H))
    main_airfoil_points = generate_airfoil(chord_length=8, angle_of_attack=-20, translate_x=0.2, translate_y=0.5)
    sorted_main_airfoil_points = sort_points_counter_clockwise(main_airfoil_points)
    vertical_offset = 0.345 
    flap_width = 0.01  
    flap_points = create_rectangular_flap(main_airfoil_points, flap_width, 0.2, 0.6, vertical_offset)
    rotation_center = min(flap_points, key=lambda pt: pt[0])  # Hinge point 
    rotated_flap_points = [rotate_point(pt, **current_flap_angle**, rotation_center) for pt in flap_points]
    sorted_flap_points = sort_points_counter_clockwise(rotated_flap_points)
    main_airfoil = mshr.Polygon([Point(x, y) for x, y in sorted_main_airfoil_points])
    flap = mshr.Polygon([Point(x, y) for x, y in sorted_flap_points])

    domain = channel - main_airfoil - flap
    mesh = mshr.generate_mesh(domain, 100)

    # Define the boundaries
    inlet_boundary = AutoSubDomain(lambda x: near(x[0], 0))  # Inlet at x = 0
    outlet_boundary = AutoSubDomain(lambda x: near(x[0], L))  # Outlet at x = L
    wall_boundary = AutoSubDomain(lambda x: near(x[1], 0) or near(x[1], H))  # Walls at y = 0 and y = H
    airfoil_boundary = AirfoilBoundary(sorted_main_airfoil_points)
    flap_boundary = FlapBoundary(sorted_flap_points,sorted_main_airfoil_points)  
    
    # Mark the boundaries
    boundaries = MeshFunction("size_t", mesh, mesh.topology().dim() - 1)
    boundaries.set_all(0)
    inlet_boundary.mark(boundaries, 1)
    wall_boundary.mark(boundaries, 2)
    outlet_boundary.mark(boundaries, 3)
    airfoil_boundary.mark(boundaries, 4)  # Assuming 4 is the airfoil boundary
    flap_boundary.mark(boundaries, 5)  # Assuming 5 is the flap boundary
    
    # Define the domain
    domains = MeshFunction("size_t", mesh, mesh.topology().dim())
    domains.set_all(1)

    return mesh, domains, boundaries

def initiate(**namespace):
    # Lists to hold displacement, forces, and time
    drag_list = []
    lift_list = []
    time_list = []

    return dict(drag_list=drag_list, lift_list=lift_list, time_list=time_list)
  
class Inlet(UserExpression):
    def __init__(self, Um, H, **kwargs):
        self.Um = Um
        self.H = H
        self.factor = 0
        super().__init__(**kwargs)

    def update(self, t):
            self.Um =  self.Um

    def eval(self, value, x):
        value[0] = self.Um  # Set the x-component of the velocity to the freestream velocity
        value[1] = 0  # y-component of the velocity is zero

    def value_shape(self):
        return (2,)

def create_bcs(DVP, v_deg, Um, H, boundaries, **namespace):
    inlet_velocity = Inlet(Um, H, degree=v_deg)
    u_inlet = DirichletBC(DVP.sub(1), inlet_velocity, boundaries, 1)

    u_wall = DirichletBC(DVP.sub(1), ((0.0, 0.0)), boundaries, 2)

    u_airfoil = DirichletBC(DVP.sub(1), ((0.0, 0.0)), boundaries, 4)  # Airfoil boundary

    u_flap = DirichletBC(DVP.sub(1), ((0.0, 0.0)), boundaries, 5)  # Flap boundary

    p_out = DirichletBC(DVP.sub(2), 0, boundaries, 3)  # Outlet pressure

    bcs = [u_inlet, u_wall, u_airfoil, u_flap, p_out]

    return dict(bcs=bcs, inlet=inlet_velocity)

# Example usage in the simulation loop

  
def pre_solve(t, inlet, **namespace):
    inlet.update(t)

def post_solve(t, dvp_, n, L, H,DVP, v_deg, Um, boundaries,current_flap_angle, drag_list, lift_list, time_list, mu_f, verbose, ds, namespace):
    # Get deformation, velocity, and pressure
    d = dvp_["n"].sub(0, deepcopy=True)
    v = dvp_["n"].sub(1, deepcopy=True)
    p = dvp_["n"].sub(2, deepcopy=True)
    # Compute forces
    force = dot(sigma(v, p, d, mu_f), n)
    drag_list.append(-assemble(force[0]*ds(4)))
    lift_list.append(-assemble(force[1]*ds(4)))
    time_list.append(t)
    # Print results
    if MPI.rank(MPI.comm_world) == 0 and verbose:
        print("Drag: {:e}".format(drag_list[-1]))
        print("Lift: {:e}".format(lift_list[-1]))
    **current_flap_angle = update_flap_angle(current_flap_angle)
    print(f"Current Flap Angle: {current_flap_angle}")
    new_mesh, new_domains, new_boundaries = get_mesh_domain_and_boundaries(L, H, current_flap_angle)
    return new_mesh, new_domains, new_boundaries, current_flap_angle **

def finished(drag_list, lift_list, time_list, results_folder, **namespace):
    # Store results when the computation is finished
    if MPI.rank(MPI.comm_world) == 0:
        np.savetxt(path.join(results_folder, 'Lift.txt'), lift_list, delimiter=',')
        np.savetxt(path.join(results_folder, 'Drag.txt'), drag_list, delimiter=',')
        np.savetxt(path.join(results_folder, 'Time.txt'), time_list, delimiter=',')
      
and this is how i adapted monolithic:

while t <= T + dt / 10 and not stop:  # + dt / 10 is a hack to ensure that we take the final time step t == T
    t += dt
    
    # Pre solve hook
    tmp_dict = pre_solve(**vars())
    if tmp_dict is not None:
        vars().update(tmp_dict)

    # Solve
    vars().update(newtonsolver(**vars()))

    # Update vectors
    for i, t_tmp in enumerate(times[:-1]):
        dvp_[t_tmp].vector().zero()
        dvp_[t_tmp].vector().axpy(1, dvp_[times[i+1]].vector())

    # After solve hook
    mesh, domains, boundaries, current_flap_angle = post_solve(**vars())
    # Checkpoint
    if counter % checkpoint_step == 0:
        checkpoint(**vars())

    # Store results
    if counter % save_step == 0:
        vars().update(save_files_visualization(**vars()))

**Comment by keiyamamo** [comment]
Hi @dlorod55 

As I said previously, please format the code with three backticks ``` before and after the code block. Without proper format, it is very difficult to distinguish where you put your code or comments.

**Comment by keiyamamo** [comment]
Closing for now. Feel free to reopen if necessary.
