### ISSUE TITLE
Can I simulate the self-propelled swimmer

### ISSUE THREAD

**Issue by xfdywy** [KVSlab/turtleFSI#14]
Hi,

Thanks for your great tool. 

Can I use the turtleFSI to simulate the self-propelled swimmer? How can I define the swimmer's behavior?

For example, I can prescribe the behavior by using a function of the midline of the body
![image](https://user-images.githubusercontent.com/6959554/169469196-edcebc01-c109-41d5-8728-8976fe7d81c7.png)

Or specifically, can the turtleFSI be used to simulate the environment like in the paper “Reinforcement Learning and Wavelet Adapted Vortex Methods for Simulations of Self-propelled Swimmers”?

Thank you very much for your help.

**Comment by keiyamamo** [comment]
Hi @xfdywy 

Have you found a solution to this issue?

Best,

**Comment by keiyamamo** [comment]
Closing this issue.  Please feel free to reopen if necessary.
