### ISSUE TITLE
The result doesn't deform in the visualization

### ISSUE THREAD

**Issue by Han10th** [KVSlab/turtleFSI#17]
I run the demo problems: turtle_demo and TF_fsi. The result doesn't deform as illustrated in the attached GIF on the readme page when I input them into ParaView. I think it may because I didn't input those files in the correct way.

Can someone tell me how should I import the XDMF and H5 files to ParaView?

**Comment by keiyamamo** [comment]
Hi @Han10th 
You need to apply `warp by vector` filter to see the movements. I think this information should be mentioned somewhere in the documents.

**Comment by Han10th** [comment]
Thanks for your reply. Where do I need to do `warp by vector` filter? In the turtleFSI or the ParaView.

**Comment by keiyamamo** [comment]
Hi @Han10th 
It is a filter in the Paraview.

**Comment by Han10th** [comment]
Thanks. I guess I should use displacement.xdmf to warp the grid rather than velocity.xdmf or presure.xdmf, right?

**Comment by keiyamamo** [comment]
Yes, that’s right!

**Comment by Han10th** [comment]
Thanks very much for helping me. BTW, it's not mentioned in the documents.

**Comment by keiyamamo** [comment]
Yes, I agree with you that it should be mentioned in the documents.

**Comment by Han10th** [comment]
Thanks again. Your answers help me a lot. Really appreciate it.
