### ISSUE TITLE
Questions regarding Python versions

### ISSUE THREAD

**Issue by jorgensd** [KVSlab/turtleFSI#25]
In the documentation it is stated that Python >=3.5 is required.
However, to use the full version of `turtleFSI`, `fenicstools` and `cppimport` is required.
`cppimport` does not support Python < 3.7.

Should the documentation really state that Python >=3.7 is required?

**Comment by jorgensd** [comment]
> Doesn't `cppimport` support Python 3.6 also?

cppimport depends (https://github.com/tbenthompson/cppimport/blob/main/setup.py#L9) on Mako (https://pypi.org/project/Mako/) which only supports python 3.7 and upwards. Python 3.6 has reached End Of Life half a year ago, so I think we could skip that as well.

It is unclear how things depend on each-other in turtle. The docs says one thing, and you get tons of warnings without cppimport due to the probes. I think it would be good to iron out what are dependencies, and what should be where.

**Comment by johannesring** [comment]
Yes, I agree that we can skip Python 3.6 and that we should look into the dependencies.
