### ISSUE TITLE
How to get the same post results as the example case shown in turtleFSI

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#26]
Thanks for the great work on this solver.

I ran the example cases of TF_fsi, and it ran and finished without any errors, but seeing the xdmf files in the 'TF_fsi_results\1\Visualization' I think the velocity contour is not the fsi result, because I didn't see any mesh deformation in the contour.

![my velocity contour](https://user-images.githubusercontent.com/97109440/205446992-624285a2-ca4f-4093-b757-6bf0bb981628.jpg)

I think the demo fig is right, and it is really different from my contour. This is really strange.
![fsi_illu](https://user-images.githubusercontent.com/97109440/205447183-a625aac1-4603-4fd6-a996-09230421bf58.png)

But when I check the output x and y displacements and lift and drag, they are well presented. 
![disp_y](https://user-images.githubusercontent.com/97109440/205447047-6f5ad2ab-6d31-47ee-9cb7-2a7f3c0d49fa.jpg)

May I know how to get the right contour shown in this website?
Which software do you use?
Is my test simulation wrong or is it just the way of postprocessing?

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 
You need to apply 'warp by vector' filter from Paraview to 'deformation.xdmf' to see the mesh deformation.

**Comment by zhangmuElias** [comment]
Thanks for your reply!
I added this filter to deformation.xdmf, and it can show the mesh deformation. 
![1670080470325](https://user-images.githubusercontent.com/97109440/205448015-f90756b6-24de-4eeb-9d56-28a5089e3062.jpg)

So I guess I can't show the deformation just using the velocity.xdmf but need the velocity.xdmf and deformation.xdmf together? And also is there a way to separate the mesh of solid part and fluid part? In this contour, the two domains are still mixed together. 
![1670080775826](https://user-images.githubusercontent.com/97109440/205448301-0b11ddfa-4bb0-4e59-a044-71cc6c4d8a52.jpg)

**Comment by keiyamamo** [comment]
No, you can't see the deformation from the velocity only. You can use 'Append attributes' in Paraivew to combine velocity and deformation and visualize velocity while mesh is deformed based on the 'deformation.xdmf'.

There's a way to separate fluid and solid domain, but you would have to use FEniCS function and save the mesh based on the domain id given to each fluid and solid.

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 
I tried your suggestions and it works well. Thank you!
And as for the separation, I will try later.

![1670083377033](https://user-images.githubusercontent.com/97109440/205450191-28cd1fce-52df-4f46-9d68-e6c38cdca5b9.jpg)
