### ISSUE TITLE
`setup.py` not working properly 

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/turtleFSI#33]
When I run 
```
python setup.py install
```
on my local machine or cluster, I get the following error message
```
No local packages or working download links found for fenics-dolfin
error: Could not find suitable distribution for Requirement.parse('fenics-dolfin')
```
I believe it is due to the recent update at the following line. 
https://github.com/KVSlab/turtleFSI/blob/e1b5350f5f105487bd77b811796f24e3b6075ea2/setup.py#L6
I remember it worked fine without this fenics-dolfin dependencies before, so I’m wondering if we need it. 
Could @jorgensd  comment on this?

**Comment by jorgensd** [comment]
That's quite strange, as it should really find `fenics-dolfin` on your system, as that is the python module used inside TurtleFSI.
Could you post the output of
`python --version`
`python -m pip list`
`python -c "import dolfin; print(dolfin.__version__)"`

**Comment by keiyamamo** [comment]
I see. I usually run `setup.py` on login-node without any sourcing but it works perfect after activating fenics. Thanks for your answer!
