### ISSUE TITLE
Which boundaries should be chosen to be included in bc_ids[]?

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#34]
Good day dear evryone:

I'm now trying to construct my own fsi case through gmsh to generate msh file to hdf5 file.
And that would need to use my own boundaries id number to set the case file.
Now I'am confused what boundaries should be chosen to be included in bc_ids[]?

In the TF_FSI case file,  I think the [2,3,4,6] refer to inlet outlet wall and cylinder. Is my guess right?
```
# TF_FSI
        # Problem specific
        folder="TF_fsi_results",      # Name of the results folder
        extrapolation="biharmonic",   # No displacement to extrapolate
        extrapolation_sub_type="constrained_disp_vel",  # Biharmonic type
        bc_ids=[2, 3, 4, 6],          # Ids of makers for the mesh extrapolation
    
    # Mark boundaries
    Allboundaries = DomainBoundary() 
    boundaries = MeshFunction("size_t", mesh, mesh.geometry().dim() - 1)
    boundaries.set_all(0)        
    Allboundaries.mark(boundaries, 1)   
    Wall.mark(boundaries, 2)         
    Inlet.mark(boundaries, 3)       
    Outlet.mark(boundaries, 4)       
    Bar.mark(boundaries, 5)             
    Circle.mark(boundaries, 6)          
    Barwall.mark(boundaries, 7)         
```

and in the turtle_demo.py case file, it didn't define any bc_ids. that's confusing, because there are not the _extrapolation_sub_type_ named _constrained_disp_ in module file biharmonic.py, how can it know how to proceed with _constrained_disp_ type?
```
 # turtle_demo.py
        extrapolation="biharmonic",    # Laplace, elastic, biharmonic, no-extrapolation
        extrapolation_sub_type="constrained_disp",  # ["constant", "small_constant", "volume", "volume_change", "constrained_disp", "constrained_disp_vel"]
```
```
 # biharmonic.py
    alpha_u = 0.01
    F_ext1 = alpha_u * inner(w_["n"], beta) * dx_f - alpha_u * inner(grad(d_["n"]), grad(beta)) * dx_f
    F_ext2 = alpha_u * inner(grad(w_["n"]), grad(phi)) * dx_f

    if extrapolation_sub_type == "constrained_disp_vel":
        for i in bc_ids:
            F_ext1 += alpha_u*inner(grad(d_["n"]) * n, beta) * ds(i)
            F_ext2 -= alpha_u*inner(grad(w_["n"]) * n, phi) * ds(i)

    F_fluid_linear += F_ext1 + F_ext2

    return dict(F_fluid_linear=F_fluid_linear)

```

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

I agree that the structure of `biharmonic.py` is confusing. My understanding is that you do not get any boundary terms with `extrapolation_sub_type=“constrained_disp”` and therefore you do not need `bc_ids` as in `turtle_demo.py`. `bc_ids` should only be given when you use `extrapolation_sub_type == "constrained_disp_vel”`.

Regarding `extrapolation_sub_type == "constrained_disp_vel”`, this boundary condition seems to have several constraints. It can only be applied to the rectangular domain with mesh motion only in the perpendicular direction of the fluid boundary. I’m not 100% sure but it seems like `extrapolation_sub_type == "constrained_disp_vel”` is specifically designed for `TF_fsi` case and special care must be taken if you want to apply such boundary conditions to your original problem. I myself have never used `extrapolation_sub_type == "constrained_disp_vel”` and thus I might misunderstand something here. 

The biharmonic mesh model is explained in the following master thesis p.21, 23

https://www.duo.uio.no/handle/10852/60349
or
https://www.sciencedirect.com/science/article/pii/S0045794911000629?via%3Dihub

So, I highly recommend that you check both of them. 

Best,
Kei

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 

Thanks for your answer and your recommended literatures! 
I think you are right, and I have changed the `extrapolation_sub_type="constrained_disp"` as the turtledemo.py wrote. Les me see if it will run to the end time.
And do you think it made any differences when choosing different sub type `["constant", "small_constant", "volume", "volume_change", "constrained_disp"]` ? 

Best regards
Zhang

**Comment by keiyamamo** [comment]
Yes, they do make differences. These two literatures that I recommended both explored such a difference. 

Best,
Kei
