### ISSUE TITLE
Confirmation of a parameter of a standard case FSI3

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#37]
Dear everyone,

I just found that there may be something confused me for the material settings of the benchmark case FSI3 in the case file `TF_fsi.py`
The first lame coefficient is set to be 4e6 but it may should be 8e6 from the paper.
```
        # Physical constants ('FSI 3')
        Um=2.0,                       # Max. velocity inlet, CDF3: 2.0 [m/s]
        rho_f=1.0e3,                  # Fluid density [kg/m3]
        mu_f=1.0,                     # Fluid dynamic viscosity [Pa.s]
        rho_s=1.0e3,                  # Solid density[kg/m3]
        nu_s=0.4,                     # Solid Poisson ratio [-]
        mu_s=2.0e6,                   # Shear modulus, CSM3: 0.5E6 [Pa]
        lambda_s=4e6,                 # Solid 1st Lame Coefficient [Pa]
```
![图片2](https://user-images.githubusercontent.com/97109440/221605053-f621f0c2-7dde-4c1c-8997-533de890e6fe.png)

Although the differences between 4e6 and 8e6 of first lame coefficient to calculate Elastic modulus is not too big, which are 5.333e6 and 5.6e6 pa.

Best regards
Zhang

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

Thank you for reporting this! Your calculation seems right to me and the first lame coefficient should be updated although I agree with you that the difference in the Elastic modulus is relatively small. 

Best,

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 

Good to hear it, and thanks for replying!

Best wishes
ZHANG
