### ISSUE TITLE
A question about CSM case

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#53]
Dear everyone

When studying the Demo case TF_CSM, I got a question about the result.
As this case simulated an elastic beam adding **only** the gravitational force, I think the beam will start to deform and vibrate initially. However, the vibration amplitude will decrease and keep still at last. 
Why the simulation results show it keeps vibrating?
I am not questioning the accuracy of this result because the reference paper also has this phenomenon. But I just don't know why the vibration will not decrease.

Best regards

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

In reality, there is damping effect (for example, air friction) that decreases the vibration, but there is no damping effect in the simulation unless you include the damping effect in the model. In `TF_CSM`, gravitational force keeps supplying the energy to the system while there is no damping effect in the system, hence no decrease in the vibration. We have therefore added a capability to simulate such a damping through so-called Robin boundary condition that mimics the behavior of damping. You can see this [problem](https://github.com/KVSlab/turtleFSI/blob/master/turtleFSI/problems/RobinBC_validation.py ) to check how it works. Hope it helps!

Best,
Kei

**Comment by zhangmuElias** [comment]
Dear @keiyamamo

Thank you, I see now.
