### ISSUE TITLE
Some questions in the solid.py

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#55]
Dear everyone

While I was reading the `modules/solid.py` , I got a few questions:

**1.** 
The penalty function method is used to make sure v = d(d)/dt
And v = d(d)/dt has been changed to 
![image](https://user-images.githubusercontent.com/97109440/236136012-21387b0e-4750-46ac-a9da-7525d312d413.png)
This is really like the idea of the central difference. 
And here, I don't know why to multiply phi(related to displacement) instead of psi(related to velocity)? 
And as there has already a huge delta(1e7), will it have a difference if the parameter rho_s is removed?
Also this part represents `rho_s*v_*δΔd` is not fitting to the first Temporal term `rho_s*a_*δΔv`, how can the penalty part directly be added to the `F_solid_linear`? 
![image](https://user-images.githubusercontent.com/97109440/236137337-3e0eefe8-7651-447f-bca4-ba008b542420.png)

```
        ## Temporal term and convection 
        F_solid_linear +=  (rho_s/k * inner(v_["n"] - v_["n-1"], psi)*dx_s[solid_region]
                                   + delta * rho_s * (1 / k) * inner(d_["n"] - d_["n-1"], phi)                * dx_s[solid_region]
                                    - delta * rho_s * inner(theta0 * v_["n"] + theta1 * v_["n-1"], phi) * dx_s[solid_region]) 
```

**2.**  
for all the F linear part and nonlinear part in solid domain
The code includes the following:
```
        ## Temporal term and convection 
        F_solid_linear += (rho_s/k * inner(v_["n"] - v_["n-1"], psi)*dx_s[solid_region]
                          + delta * rho_s * (1 / k) * inner(d_["n"] - d_["n-1"], phi) * dx_s[solid_region]
                          - delta * rho_s * inner(theta0 * v_["n"] + theta1 * v_["n-1"], phi) * dx_s[solid_region]) # Maybe we could add viscoelasticity with v["n"] term instead of (1 / k) * inner(d_["n"] - d_["n-1"], phi) 
        
        # Stress (Note that if viscoelasticity is used, Piola1() is no longer the total stress, it is the non-rate dependant (elastic) component of the stress)
        F_solid_nonlinear += theta0 * inner(Piola1(d_["n"], solid_properties[solid_region]), grad(psi)) * dx_s[solid_region]
        F_solid_linear += theta1 * inner(Piola1(d_["n-1"], solid_properties[solid_region]), grad(psi)) * dx_s[solid_region]
        # Gravity
        if gravity is not None and mesh.geometry().dim() == 2:
            F_solid_linear -= inner(Constant((0, -gravity * rho_s)), psi)*dx_s[solid_region] 
```
And I write it into formulas, and I also don't know what's the purpose of the term (1)(2)(3)(5) to multiply psi(related to velocity) instead of psi(related to velocity). I guess it is to use the concept of rate of work instead of work?
![image](https://user-images.githubusercontent.com/97109440/236140228-e62a6114-f5fd-4768-bbf7-ecc993618e22.png)
 
Any help would be greatly appreciated.

Best regards
ZHANG

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

For the choice of test function, we follow the formulation by [this PhD thesis](https://archiv.ub.uni-heidelberg.de/volltextserver/12992/) in which the structure problem is formulated as 

![Screenshot 2023-05-05 at 10 52 59](https://user-images.githubusercontent.com/42674006/236416254-bbc0ef5b-939b-4fc6-875a-b9b546a5b8c1.png)

In our case, we do not include damping term so $\gamma_{\omega}$ = $\gamma_s = 0$. Unfortunately, I cannot find the explanation about the choice of particular test function for each equation in the thesis, but I assume it is related to the stability or continuity necessary for the well-posedness of the problem. I think the choice of test functions come from functional  Because of the mixed formulation between elastic and continuity equation, I do not think you can have the same test function for both of the equations. In our case, it might still work even if you switch phi and psi in all the formulations because we use the same finite element for the displacement and velocity, but I’m not sure if that’s worth investigating.

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 

Thanks again for answering me every time for my question. It really helped me a lot!
There is one thing I want to make sure about what you said: 

> it might still work even if you switch phi and psi in all the formulations

Do you mean if the phi is used for the elastic equation and psi for the continuity equation, it will still go well for this code?
What only matters is to use different test functions for the elastic and continuity equations?

Also, I can test this thought on my computer.

Best regards
Runze ZHANG

**Comment by keiyamamo** [comment]
Hi @zhangmuElias  

What is the motivation for you to switch test functions? My apology for the confusing my last reply, I honestly do not know if it will work or not. More accurately, I was thinking " (Switching test functions should not work if we had different finite element or polynomial order between displacement and velocity, but we use the same element with the same order on the same mesh, so ) it might still work."

**Comment by keiyamamo** [comment]
Have you changed `no_fluid.py` as well ? There is also psi and phi there although I'm not sure if that matters.

**Comment by zhangmuElias** [comment]
Yes, the original no_fluid.py writes:
```
        F_fluid_linear +=    inner(Constant(tuple([0] * mesh.geometry().dim())), psi) * dx_f[fluid_region]
        F_fluid_nonlinear += inner(Constant(tuple([0] * mesh.geometry().dim())), phi) * dx_f[fluid_region]
```
I changed it to:
```
        F_fluid_linear += inner(Constant(tuple([0] * mesh.geometry().dim())), phi) * dx_f[fluid_region]
        F_fluid_nonlinear += inner(Constant(tuple([0] * mesh.geometry().dim())), psi) * dx_f[fluid_region]
```
Actually, I tried both these two type, and they show the same errors.

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

Please have a look at [here](https://fenicsproject.discourse.group/t/aritymismatch-in-nonlinear-heat-equation-in-1d/6655) or [here](https://fenicsproject.org/qa/11415/what-do-aritymismatch-errors-really-mean/). In `turtleFSI`, we do not really expect variational form to be changed, so unfortunately I cannot spend too much time on that.

**Comment by zhangmuElias** [comment]
As for what I am doing.

I already tried successfully coded the geometry linear (small deformation) solid problem with the piezoelectric field in fenics. 
Because I want to study the piezoelectric energy harvester in fsi, I am now trying to expand the piezoelectric field for turtlefsi.
![image](https://user-images.githubusercontent.com/97109440/236472931-8cda6277-5be4-4209-81b8-1f0c288f45f4.png)

I changed the solid.py into
```
    for solid_region in range(len(dx_s_id_list)):
        rho_s = solid_properties[solid_region]["rho_s"]

        ## Temporal term and convection 
        F_solid_linear += (rho_s/k * inner(v_["n"] - v_["n-1"], psi)*dx_s[solid_region]
                          + delta * rho_s * (1 / k) * inner(d_["n"] - d_["n-1"], phi) * dx_s[solid_region]
                          - delta * rho_s * inner(theta0 * v_["n"] + theta1 * v_["n-1"], phi) * dx_s[solid_region]) # Maybe we could add viscoelasticity with v["n"] term instead of (1 / k) * inner(d_["n"] - d_["n-1"], phi) 


        # Stress (Note that if viscoelasticity is used, Piola1() is no longer the total stress, it is the non-rate dependant (elastic) component of the stress)
        F_solid_nonlinear += theta0 * inner(Piola1_piezo(d_["n"],φ_["n"], solid_properties[solid_region]), grad(psi)) * dx_s[solid_region]
        F_solid_linear += theta1 * inner(Piola1_piezo(d_["n-1"],φ_["n-1"], solid_properties[solid_region]), grad(psi)) * dx_s[solid_region]

        # piezo part non
        F_solid_linear +=  (delta *  (1 / k) * dot(φ_["n"] - φ_["n-1"], phi_e) * dx_s[solid_region]
                          - delta *  dot(theta0 * Φ_["n"] + theta1 * Φ_["n-1"], phi_e) * dx_s[solid_region])  # Maybe we could add viscoelasticity with v["n"] term instead of (1 / k) * inner(d_["n"] - d_["n-1"], phi)
        F_solid_nonlinear -= theta0* dot(e_disp(d_["n"],φ_["n"], solid_properties[solid_region]), -grad(psi_e)) * dx_s[solid_region]
        F_solid_linear -= theta1* dot(e_disp(d_["n-1"],φ_["n-1"], solid_properties[solid_region]), -grad(psi_e)) * dx_s[solid_region]

        # Gravity
        if gravity is not None and mesh.geometry().dim() == 2:
            F_solid_linear -= inner(Constant((0, -gravity * rho_s)), psi)*dx_s[solid_region] 
        elif gravity is not None and mesh.geometry().dim() == 3:
            F_solid_linear -= inner(Constant((0, -gravity * rho_s,0)), psi)*dx_s[solid_region] 
```
Although when I ran my code, it didn't give errors but it diverged in the first time step.
Compute Jacobian matrix
N```
ewton iteration 21: r (atol) = 5.307e+07 (tol = 1.000e-07), r (rel) = 2.888e+18 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 22: r (atol) = 6.191e+07 (tol = 1.000e-07), r (rel) = 1.283e+18 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 23: r (atol) = 5.190e+07 (tol = 1.000e-07), r (rel) = 5.865e+18 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 24: r (atol) = 9.419e+07 (tol = 1.000e-07), r (rel) = 2.264e+19 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 25: r (atol) = 2.537e+08 (tol = 1.000e-07), r (rel) = 9.836e+17 (tol = 1.000e-07) 
Compute Jacobian matrix
Traceback (most recent call last):
  File "/home/dell-123/anaconda3/envs/turtlefsiproject/bin/turtleFSI_master_piezo", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/dell-123/anaconda3/envs/turtlefsiproject/lib/python3.11/site-packages/turtleFSI/run_turtle_master_piezo.py", line 18, in main
    from turtleFSI import monolithic_master_piezo
  File "/home/dell-123/anaconda3/envs/turtlefsiproject/lib/python3.11/site-packages/turtleFSI/monolithic_master_piezo.py", line 180, in <module>
    vars().update(newtonsolver(**vars()))
                  ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/dell-123/anaconda3/envs/turtlefsiproject/lib/python3.11/site-packages/turtleFSI/modules_master/newtonsolver.py", line 92, in newtonsolver
    raise RuntimeError("Error: The simulation has diverged during the Newton solve.")
RuntimeError: Error: The simulation has diverged during the Newton solve. 
```

**Comment by keiyamamo** [comment]
This `delta` term could be specific to the problem and should not really be hard-coded in my opinion. If you are adding term to the continuity equation, you might have to tune the value, assuming your variational formulation is correct (which I cannot tell since I'm not familiar with your topic).

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 
You have already helped a lot. Thank you!
Ok, let me try different delta to see what will happen.

**Comment by keiyamamo** [comment]
Closing. Feel free to reopen if necessary @zhangmuElias
