### ISSUE TITLE
Definitions of some quantities inside newtonsolver

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#58]
Dear everyone:

The core calculating part inside newtonsolver writes:
```
        if recompute_for_timestep or recompute_frequency or recompute_residual or recompute_initialize:
            if MPI.rank(MPI.comm_world) == 0 and verbose:
                print("Compute Jacobian matrix")
            A = assemble(J_nonlinear, tensor=A,
                         form_compiler_parameters=compiler_parameters,
                         keep_diagonal=True)
            A.axpy(1.0, A_pre, True)
            A.ident_zeros()
            [bc.apply(A) for bc in bcs]
            up_sol.set_operator(A)

        # Compute right hand side
        b = assemble(-F, tensor=b)

        # Apply boundary conditions and solve
        [bc.apply(b, dvp_["n"].vector()) for bc in bcs]
        up_sol.solve(dvp_res.vector(), b)
        dvp_["n"].vector().axpy(lmbda, dvp_res.vector())
        [bc.apply(dvp_["n"].vector()) for bc in bcs]
```
And in my understanding, for turtlefsi, in each time step, we will calculate the increments of displacement, velocity and pressure and then add the increments part to the old displacement, velocity and pressure.
Does it mean:
trialfunction `chi` mean real Δd  Δv Δp
testfunction  `psi phi gamma` mean virtual  δ(Δd)  δ(Δv) δ(Δp)
Most importantly, if `dvp_res` is for storing the results of real Δd  Δv Δp  (the increments of displacement, velocity and pressure)

Only one thing I am sure about: 
`dvp_["n"]` means displacement, velocity and pressure at time step n,
`dvp_["n-1"] `means displacement, velocity and pressure at time step n-1,

Do I understand right for these quantities?

Best regards
Zhang

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

I think your understanding is correct. Although I do not really understand what you mean by virtual δ(Δd) δ(Δv) δ(Δp), but yes they are testfunctions for each variables. 
For each Newton iteration, we are solving 
```math
J_{F}(x_k)s = -F(x_{k})
```
```math
x_{k+1} = x_{k} + s
```
where $J_{F}$ is the Jacobian (`A` in turtleFSI), $x_{k}$ is the solution we are looking for (`dvp_["n"]` in turtle), and `s` is a vector that represents each "Newton step" and the one we are actually solving for (`dvp_res` in turtle).

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 

Thank you! I also don't understand why in the newton solver, we need to apply so many times the boundary conditions. 
They must have different kinds of functions?

Best regards
ZHANG

**Comment by keiyamamo** [comment]
```
[bc.apply(b, dvp_["n"].vector()) for bc in bcs]
```
This is to make sure that both `b` and `dvp_["n"].vector()` satisfies the boundary condition before we solve the linear system. After solving the linear system, we add the residual to the `dvp_["n"]` 

```
dvp_["n"].vector().axpy(lmbda, dvp_res.vector())
```
However, the residual does not necessary satisfy the boundary condition and thus we need to make sure `dvp_["n"]`  satisfies the boundary condition after that by calling 
```
[bc.apply(dvp_["n"].vector()) for bc in bcs]
```

**Comment by zhangmuElias** [comment]
Ok! That's very clear, thank you.
