### ISSUE TITLE
Error in visualization of results in paraview (TF_fsi)

### ISSUE THREAD

**Issue by Panchal1810** [KVSlab/turtleFSI#60]
Hello !

I ran tutorial case TF_fsi with default parameters. I am facing issue while visualizing the velocty, pressure and displacement (.xdmf format) in paraview. I checked the data in another HDF5 viewer, it shows the data in array format. But, information of time is not perfectly visible. If possible, can I change writing file format ?

**Comment by jorgensd** [comment]
Could you elaborate on what issues you get when you try to visualize it in Paraview?

**Comment by keiyamamo** [comment]
Could be related to #16

**Comment by keiyamamo** [comment]
Hi @Panchal1810  

Did you use `conda-forge` to install `turtleFSI`? 
In that case, I recommend that you re-install `turtleFSI` with following steps. 
First, clone the repository
```
git clone https://github.com/KVSlab/turtleFSI.git
```
Move to where you cloned the turtleFSI
```
cd turtleFSI
```
and create a conda environment with your choice of the name, replace `your_environment_name` with any name you want
```
conda env update --file environment.yml --name your_environment_name
```
and run
```
python3 -m pip install --editable .
```

**Comment by keiyamamo** [comment]
Hi @Panchal1810 

Could you check which version of `scipy` is installed in your environment?
According to here :https://stackoverflow.com/questions/72540359/glibcxx-3-4-30-not-found-for-librosa-in-conda-virtual-environment-after-tryin
The problem might be solved by downgrading the version of `scipy`.

**Comment by Panchal1810** [comment]
After downgrading the python version to 3.7 using following command:

conda install python=3.7

finally, I successfully run the tutorial case TF_fsi but, still  unable to visualize the data (velocity, pressure and displacement in .XDMF format) in paraview.

In paraview, I am getting following errors:

![image](https://github.com/KVSlab/turtleFSI/assets/122630851/475667a1-8bfc-4fb9-9caa-671251231c03)

![image](https://github.com/KVSlab/turtleFSI/assets/122630851/f8fbe690-3c91-485c-bddd-8da9a4bf9f60)

I don't what cause this problem.

**Comment by jorgensd** [comment]
> After downgrading the python version to 3.7 using following command:
> 
> conda install python=3.7
> 
> finally, I successfully run the tutorial case TF_fsi but, still unable to visualize the data (velocity, pressure and displacement in .XDMF format) in paraview.
> 
> In paraview, I am getting following errors:
> 
> ![image](https://user-images.githubusercontent.com/122630851/240581509-475667a1-8bfc-4fb9-9caa-671251231c03.png)
> 
> ![image](https://user-images.githubusercontent.com/122630851/240581602-f8fbe690-3c91-485c-bddd-8da9a4bf9f60.png)
> 
> I don't what cause this problem.

Could you add the output of the xdmf-file here?

**Comment by Panchal1810** [comment]
In the output, the paraview directly aborted (unable to see the contain of the file). Here, I also attached the XDMF format files. 

[files.zip](https://github.com/KVSlab/turtleFSI/files/11554199/files.zip)

**Comment by jorgensd** [comment]
> In the output, the paraview directly aborted (unable to see the contain of the file). Here, I also attached the XDMF format files.
> 
> [files.zip](https://github.com/KVSlab/turtleFSI/files/11554199/files.zip)

This looks like the issue: https://bitbucket.org/fenics-project/dolfin/pull-requests/555
which should be resolved on conda as well: https://github.com/conda-forge/fenics-feedstock/blob/main/recipe/fix-xdmf.patch

**Comment by keiyamamo** [comment]
Closing this for now. Feel free to reopen @Panchal1810
