### ISSUE TITLE
Pressure should not be part of save_deg >1 ?

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/turtleFSI#61]
https://github.com/KVSlab/turtleFSI/blob/d149375c2d89f17e5662f352e4547ffd1a471750/turtleFSI/problems/__init__.py#L235-L247

Since we use `p_deg=1` for most of the case, it does not make sense that the pressure is part of `save_deg >1` functionality.
We should check if the original degree is actually higher than 1st order before calling `save_deg>1` part. Otherwise, we are interpolating the  P1 solution from coarse to fine mesh.

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

No, the solver should be able to handle higher order element for the pressure. I just tested `d_deg=v_deg=p_deg=2` and it works fine. The reason for `p_deg=1` comes from the known fact `v_deg=2, p_deg=1` tends to be more stable than `v_deg=p_deg=1`. Originally, this stable combination comes from Stokes problem and thus strictly this does not apply to `turtleFSI` since we are solving full Navier-Stokes equations. However, due to higher accuracy with `v_deg=2`, we prefer using `v_deg=2` and `p_deg=1`. I used `d_deg=v_deg=3` and `p_deg=2` previously on the cluster and it worked well, but it becomes computationally very(!) expensive. I believe the divergence I had on my laptop actually comes from the lack of memory.

**Comment by zhangmuElias** [comment]
Thanks, @keiyamamo.
Speaking of cluster. I tried using parallel running, and what I run in the commander is `mpirun -np 10 turtleFSI -p TF_fsi`. I don't know if this is the right way to perform parallel computation. Because when I tested the TF_fsi case, the computation time actually didn't reduce obviously, and even became longer when I used 20 cores.  Is this a normal situation?
As in my experience of using OpenFOAM, it is needed to settle the decomposite parts of the computation domain. Do we need to do this in turtlefsi?

Best regard
ZHANG

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 

Ok, I see. In my case, I increased the mesh element number to 20000 to model the thin plate vibration. The fsi solver would take 200 seconds for one time step. 
Is there a way to accelerate the calculation? I think my computer has enough resources to deal with such a 2d problem. 
When I monitored the CPU and memory used during the calculation,  it read:
<img width="418" alt="1686774848526" src="https://github.com/KVSlab/turtleFSI/assets/97109440/b90053cf-e737-4467-8de3-d173aa41043c">
<img width="417" alt="1686774879852" src="https://github.com/KVSlab/turtleFSI/assets/97109440/a7079b48-cfec-4064-b26e-899f54f3be47">

Would you know how to fully use my computer to run the fsi cases?

<img width="1102" alt="1686774534747" src="https://github.com/KVSlab/turtleFSI/assets/97109440/04e3a5e9-8a77-4779-a5ab-ed4fae4b24ef">
<img width="865" alt="1686774764070" src="https://github.com/KVSlab/turtleFSI/assets/97109440/1f410f65-e5b3-4599-9ede-6bc04d49238c">

**Comment by keiyamamo** [comment]
Does it take 200 seconds when you recompute Jacobian or without recomputing Jacobian? If it takes 200 seconds even without recomputing Jacobian, I can only think of using more than single processor (but not probably 10 cores). If it takes 200 seconds with recomputing Jacobian, you can try increasing `recompute` or `recompute_tstep`. The other thing you can change is the tolerance for Newton solver. What is your current value for `recompute`, `recompute_tstep`, and `a/rtol`?

**Comment by zhangmuElias** [comment]
In fact, I did't change the default value because I don't know if I change these, the solver will diverge or not.

```
    # Solver settings
    linear_solver="mumps",                     # use list_linear_solvers() to check alternatives
    solver="newtonsolver",                     # newtonsolver, there is currently no other choices.
    atol=1e-7,                                 # absolute error tolerance for the Newton iterations
    rtol=1e-7,                                 # relative error tolerance for the Newton iterations
    max_it=50,                                 # maximum number of Newton iterations
    lmbda=1.0,                                 # [0, 1.0] Cst relaxation factor for the Newton solution update
    recompute=5,                               # recompute the Jacobian after "recompute" Newton iterations
    recompute_tstep=1,                         # recompute the Jacobian after "recompute_tstep" time steps (advanced option: =1 is preferred)
    compiler_parameters=_compiler_parameters,  # Update the default values of the compiler arguments (FEniCS)

    save_step=1,                    # Save file frequency
    recompute=1,                  # Compute the Jacobian matrix every iteration
```


![image](https://github.com/KVSlab/turtleFSI/assets/97109440/0614e725-0b96-4bec-a898-83f00528ff0e)

**Comment by keiyamamo** [comment]
Is this the newton iteration from your own problem?

**Comment by keiyamamo** [comment]
I see. Your newton iteration does not look so “healthy” to me. It does converge, but very slow convergence even with recomputing Jacobian, which is not a good sign. Does it always take more than 17 iterations to converge? What happens when you recompute Jacobian is that the linear solver needs to perform whole LU factorization due to the fact that matrix A changes and it is an expensive computation. So,  you want to reduce the number of recomputing Jacobian to speed up the solver but that does not seem to work in your case... Does it diverge if you set `recompute=5 or 10`?  Computing Jacobian every iteration is very costly.

**Comment by zhangmuElias** [comment]
> Does it always take more than 17 iterations to converge?

Yes, it needs more than 17 iterations when the deformations become large.




> So, you want to reduce the number of recomputing Jacobian to speed up the solver but that does not seem to work in your case...

Why do you think reducing the number of recomputing would not work for me? Is it because it might make the solver more difficult to converge?


In the followed picture, I also noticed some strange things.  Why the solver gave me results even r(atol) didn't reach the limited value 1e-7? Is this a signal of "unhealthy" you mentioned?
![image](https://github.com/KVSlab/turtleFSI/assets/97109440/76537c65-1f2b-4f2b-aa38-1173384df599)

**Comment by keiyamamo** [comment]
> Why do you think reducing the number of recomputing would not work for me? Is it because it might make the solver more difficult to converge?

It is because the residual does not decrease well during the Newton iteration. 

> In the followed picture, I also noticed some strange things. Why the solver gave me results even r(atol) didn't reach the limited value 1e-7? Is this a signal of "unhealthy" you mentioned?

It is not strange. Your relative tolerance is lower than the threshold `r (rel) = 4.000e-08 (tol = 1.000e-07)`. Newton solver stops when either of the tolerance becomes lower than the threshold. What I mean by “unhealthy” is not a good decrease in the residual even when you recompute the Jacobian. For example, you can see that the following newton iteration has nice convergence. The residual decrease from e-03, e-07, and e-09 without recomputing the Jacobian.
```
Newton iteration 0: r (atol) = 1.530e-03 (tol = 1.000e-07), r (rel) = 2.224e-03 (tol = 1.000e-06) 
Newton iteration 1: r (atol) = 5.546e-07 (tol = 1.000e-07), r (rel) = 1.574e-03 (tol = 1.000e-06) 
Newton iteration 2: r (atol) = 5.759e-09 (tol = 1.000e-07), r (rel) = 2.323e-08 (tol = 1.000e-06) 
```

**Comment by zhangmuElias** [comment]
OK, I understand now. Maybe I can loose the limit of tol from 1e-7 to 1e-4, for example. Is there anything I should notice for the setting of tol?

**Comment by keiyamamo** [comment]
The choice of the tolerance really depends on the problem and the parameter you use. For example, if the value of your interest is huge (say $10^9$), then you will most likely not achieve very small tolerance. There is a nice reference regarding the setting of Newton solver. See [here](https://fenicsproject.discourse.group/t/default-absolute-tolerance-and-relative-tolerance/3829/4?u=kei_yamamoto).

**Comment by keiyamamo** [comment]
When you say “at first step”, do you mean first iteration of the first time step? or just first time step? If it fails from the very first iteration, then the problem might be not well-posed. The problem might be related to the memory issue as described https://turtlefsi2.readthedocs.io/en/latest/known_issues.html, but not sure if it’s the case with your problem.

**Comment by zhangmuElias** [comment]
Yes, it fails from the very first iteration, but I only changed the solving domain to a bigger one.
I added the two lines code to newtownsolver.py it got the error message, do you might know what's might be the reason?
```
from dolfin import assemble, derivative, TrialFunction, Matrix, norm, MPI,PETScOptions
PETScOptions.set("mat_mumps_icntl_4", 1) # If negatvie or zero, MUMPS will suppress diagnositc printining, statistics, and warning messages.
PETScOptions.set("mat_mumps_icntl_14", 400) # allocate more memory to mumps
```

```
    up_sol.solve(dvp_res.vector(), b)
RuntimeError: 

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to solve linear system using PETSc Krylov solver.
*** Reason:  Solution failed to converge in 0 iterations (PETSc reason DIVERGED_PC_FAILED, residual norm ||r|| = 0.000000e+00).
*** Where:   This error was encountered inside PETScKrylovSolver.cpp.
*** Process: 0
*** 
*** DOLFIN version: 2019.1.0
*** Git changeset:  3ea2183fbfe7277de9f16cbe1a9ffaab133ba1fa
*** -------------------------------------------------------------------------

 ** ERROR RETURN ** FROM DMUMPS INFO(1)=  -10
 ** INFO(2)=          262336
 On return from DMUMPS, INFOG(1)=             -10
 On return from DMUMPS, INFOG(2)=          262336
```

**Comment by keiyamamo** [comment]
According to the MUMPS user guide, 
> -10 Numerically singular matrix. INFO(2) holds the number of eliminated pivots.

You can find the user guide [here](https://mumps-solver.org/doc/userguide_5.6.0.pdf)

**Comment by zhangmuElias** [comment]
Dear @keiyamamo 
Thanks, I just found out the reason why the solver gave out such an error.
It is because I used `Transfinite ` function in gmsh. While I delete the following two lines in gmsh, the solver will not diverge.
```
//Transfinite Surface {2};
//Transfinite Surface {3};

```

Also in my own working FSI case, I tried if I set `recompute=5` it will accelerate the solving speed at the first 100 time steps, but it will diverge after.
```
Solved for timestep 159, t = 1.5900 in 76.9 s
Compute Jacobian matrix
Newton iteration 0: r (atol) = 2.214e+05 (tol = 1.000e-07), r (rel) = 1.198e+01 (tol = 1.000e-07) 
Newton iteration 1: r (atol) = 8.949e+04 (tol = 1.000e-07), r (rel) = 1.499e+02 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 2: r (atol) = 7.493e+04 (tol = 1.000e-07), r (rel) = 3.492e+03 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 3: r (atol) = 2.746e+07 (tol = 1.000e-07), r (rel) = 2.072e+03 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 4: r (atol) = 1.818e+06 (tol = 1.000e-07), r (rel) = 1.730e+03 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 5: r (atol) = 6.866e+05 (tol = 1.000e-07), r (rel) = 1.478e+03 (tol = 1.000e-07) 
Newton iteration 6: r (atol) = 2.917e+06 (tol = 1.000e-07), r (rel) = 4.298e+04 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 7: r (atol) = 2.673e+09 (tol = 1.000e-07), r (rel) = 3.250e+07 (tol = 1.000e-07) 
Compute Jacobian matrix
Newton iteration 8: r (atol) = 2.363e+16 (tol = 1.000e-07), r (rel) = 3.747e+14 (tol = 1.000e-07) 
Compute Jacobian matrix
    raise RuntimeError("Error: The simulation has diverged during the Newton solve.")
RuntimeError: Error: The simulation has diverged during the Newton solve.
```

**Comment by keiyamamo** [comment]
I’m not surprised that the solver diverged. The exact behavior of the Newton solver depends on the nature of the problem and other parameters such as time step. So, I would say that you have to try different parameters and see what kind of combination works the best for your particular problem.

**Comment by zhangmuElias** [comment]
Sure, your comments are very pertinent.
One last question here, I met a weird situation where if I ran two same TF_fsi cases, the simulation time for each case would increase to two times the time if I just ran one TF_fsi case.
For example, when I run just one TF_fsi case, the time needed for solving one timestep is 10s. But if I run two TF_fsi cases simultaneously, the time needed for solving one timestep would be 20s. It seems they would influence each other. 
Did you seen such a thing before? Or it's just my computer's problem.

**Comment by keiyamamo** [comment]
I’m not a computer scientist, but it seems natural that they influence each other. Your computer has limited memory and you can only fit certain amount of data in it for fast access (memory cache). So there is some delay due to slower access of data.

**Comment by zhangmuElias** [comment]
Sure, but my memory is 120gb, it would be enough for at least two TF_fsi case. I will try to figure out why that happens. 
Thanks again for your answers!
