### ISSUE TITLE
Error in make_womersley_bcs due to numpy.complex removal

### ISSUE THREAD

**Issue by johannesring** [KVSlab/turtleFSI#69]
When calling the `make_womersley_bcs` function in the `Womersley.py` module, I get the following error message:
```
AttributeError: module 'numpy' has no attribute 'complex'.
```
`np.complex` was a deprecated alias for the builtin `complex` and has been removed in recent versions of NumPy (see https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations). The suggested solution is to use `complex` instead of `np.complex` in the code. However, if the intention was to use the numpy scalar type, `np.complex128` should be used instead. Which one should we use?

**Comment by jorgensd** [comment]
I'd suggest using `numpy.complex128`, as typing etc does not like mixing numpy dtypes and built-in data types. (Similarly i would use `np.array([1,2,3],dtype=np.float64)` instead of `float`.

**Comment by keiyamamo** [comment]
Fixed #71
