### ISSUE TITLE
`configparser` convert all key names to lowercase

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/turtleFSI#75]
I noticed that `configparser ` convert all key names to lowercase by its default. This is not a big problem but is not mentioned anywhere in our example and we actually use parameter with uppercase. As long as there is no demand for supporting upper case parameter, I will change `example.config` and `turtle_demo` to make it consistent. 

Ref. 
https://github.com/KVSlab/turtleFSI/blob/e869c8dd363b0e869f279749a66fd1203df8ef8a/docs/examples/example.config#L50

This will be treated as `um`

**Comment by johannesring** [comment]
I have several capitalized parameters in my config files and I think it would be nice to have support for this. We used to have support for this before we switched from `DefaultConfigArgParser` to `ConfigparserConfigFileParser` in PR #57. That PR adds support for dictionaries like this:
``` ini
[fluid]
fluid_properties : {
    dx_f_id: 2,
    rho_f: 1,
    mu_f: 1E3
    }
```
This does not work with `DefaultConfigArgParser`, however keeping the dictionary on one line works fine:
``` ini
fluid_properties={dx_f_id: 2, rho_f: 1, mu_f: 1E3}
```
Then we don't need the section header anymore either, which is not used anyway. 

What do you think @keiyamamo?

**Comment by johannesring** [comment]
With this patch we will keep support for the `fluid_properties` and `solid_properties` dictionaries (if they are specified on one line) and the parameters will be case sensitive like before:
``` patch
diff --git a/turtleFSI/utils/argpar.py b/turtleFSI/utils/argpar.py
index c1acedc..3ce9232 100644
--- a/turtleFSI/utils/argpar.py
+++ b/turtleFSI/utils/argpar.py
@@ -120,7 +120,7 @@ def restricted_float(x):
 
 def parse():
 
-    parser = configargparse.ArgParser(config_file_parser_class=configargparse.ConfigparserConfigFileParser, 
+    parser = configargparse.ArgParser(
             description=("turtleFSI is an open source Fluid-Structure Interaction (FSI) solver written in Python "
                         + "and built upon the FEniCS finite element library. The purpose of turtleFSI is to "
                         + "provide a user friendly and numerically robust monolithic FSI solver able to handle "

```
Please go ahead and make a PR if it works for you @keiyamamo.

**Comment by keiyamamo** [comment]
@johannesring 
I got it! Thank you :)
