### ISSUE TITLE
posssibility to extent the fluid solver to be turbulent

### ISSUE THREAD

**Issue by zhangmuElias** [KVSlab/turtleFSI#79]
Dear everyone

Recently I have been searching for a way to implement turbulent flow simulation in turtleFSI.
There is a post in fenics forum: 
https://fenicsproject.discourse.group/t/navier-stokes-simulation-getting-slower-with-time/11452
He seems to have successfully implemented the LES Smagorinsky model in FENICSX.
Do you think it is possible to extend the existing fluid model to LES in turtlefsi?

Best regards
ZHANG

**Comment by keiyamamo** [comment]
Hi @zhangmuElias 

Yes, it should be possible to add the sub-grid stress into the equation. We have CFD solver called [Oasis](https://github.com/mikaem/Oasis/tree/master/oasis/solvers/NSfracStep/LES) that has LES implementation in it, so you can see how it is implemented there.

**Comment by zhangmuElias** [comment]
Ok, thanks @keiyamamo, I will read the oasis first.
