### ISSUE TITLE
Remove parameterization over conda versions

### ISSUE THREAD

**Issue by keiyamamo** [KVSlab/turtleFSI#89]
Unfortunately, conda updates python version when we try to pin it, resulting in unnecessary usage of CI.

Try conda only with latest (python 3.10 or python 3.11)

**Comment by johannesring** [comment]
I think it would be good to test against the oldest supported Python version (3.8?) and the latest version.

**Comment by keiyamamo** [comment]
Hi @johannesring, 

The comment above was typed by @jorgensd  during the meeting today. I agree it would be nice to test against different python versions. However, it seemed that using `conda env update -n some_name -f environment.yml` updates the python version to 3.10 even when we specify different python versions. I will see if I can fix the issue!
