### ISSUE TITLE
accessing external files on docker

### ISSUE THREAD

**Issue by dlorod55** [KVSlab/turtleFSI#91]
Im currently using turtle fsi on docker and microsoft visual studio and have trouble accessing external filed and when i execute moving cylinder i get fenics@df3ab8a8010e:~/local/turtleFSI$ turtleFSI --problem MovingCylinder
{'A_ratio': 0.25,
 'D': 0.1,
 'F_r': 1.0,
 'Re': 500,
 'St': 0.228,
 'T': 5,
 'Um': 0.8,
 'atol': 1e-07,
 'bc_ids': [],
 'c_s': 0.0,
 'checkpoint_step': 500,
 'compiler_parameters': {'add_tabulate_tensor_timing': False,
                         'cache_dir': '',
                         'convert_exceptions_to_warnings': False,
                         'cpp_optimize': True,
                         'cpp_optimize_flags': '-O2',
                         'epsilon': 1e-14,
                         'error_control': False,
                         'external_include_dirs': '',
                         'external_includes': '',
                         'external_libraries': '',
                         'external_library_dirs': '',
                         'form_postfix': False,
                         'format': 'ufc',
                         'generate_dummy_tabulate_tensor': False,
                         'log_level': 25,
                         'log_prefix': '',
                         'max_signature_length': 0,
                         'no-evaluate_basis_derivatives': True,
                         'optimize': True,
                         'output_dir': '.',
                         'precision': None,
                         'quadrature_degree': 4,
                         'quadrature_rule': None,
                         'representation': 'auto',
                         'split': False},
 'counter': 0,
 'd_deg': 1,
 'ds_s_id': None,
 'dt': 0.000125,
 'dx_f_id': 1,
 'dx_s_id': 2,
 'extrapolation': 'laplace',
 'extrapolation_sub_type': 'constant',
 'factor': 50.0,
 'fluid': 'fluid',
 'fluid_properties': [],
 'folder': 'results_moving_cylinder',
 'gravity': None,
 'k_s': 0.0,
 'killtime': None,
 'lambda_s': 450000.0,
 'linear_solver': 'mumps',
 'lmbda': 1.0,
 'loglevel': 20,
 'material_model': 'StVenantKirchoff',
 'max_it': 50,
 'mu_f': 0.2,
 'mu_s': 50000.0,
 'nu_s': 0.45,
 'p_deg': 1,
 'problem': 'MovingCylinder',
 'recompute': 25,
 'recompute_tstep': 100,
 'restart_folder': None,
 'rho_f': 1000,
 'rho_s': 1000.0,
 'robin_bc': False,
 'rtol': 1e-07,
 'save_deg': 1,
 'save_step': 100,
 'solid': 'no_solid',
 'solid_properties': [],
 'solver': 'newtonsolver',
 'sub_folder': None,
 't': 0,
 'theta': 0.500125,
 'u_inf': 1.0,
 'v_deg': 1,
 'verbose': True}
Traceback (most recent call last):
  File "/usr/local/bin/turtleFSI", line 11, in <module>
    load_entry_point('turtleFSI', 'console_scripts', 'turtleFSI')()
  File "/home/fenics/local/turtleFSI/turtleFSI/run_turtle.py", line 18, in main
    from turtleFSI import monolithic
  File "/home/fenics/local/turtleFSI/turtleFSI/monolithic.py", line 63, in <module>
    mesh, domains, boundaries = get_mesh_domain_and_boundaries(**vars())
  File "/home/fenics/local/turtleFSI/turtleFSI/problems/MovingCylinder.py", line 81, in get_mesh_domain_and_boundaries  
    infile.read(mesh)
RuntimeError:

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "mesh/MovingCylinder/mesh4.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 0
***
*** DOLFIN version: 2019.1.0
*** Git changeset:  74d7efe1e84d65e9433fd96c50f1d278fa3e3f3f
*** -------------------------------------------------------------------------

fenics@df3ab8a8010e:~/local/turtleFSI$ 

Help me please

**Comment by dlorod55** [comment]
This is really important as im using it for my masters

**Comment by keiyamamo** [comment]
Hi @dlorod55,

mesh can be downloaded from [here](https://drive.google.com/drive/folders/1pCXNWfCAkG5C8dSYFowebqcPVVq9qZzB?usp=sharing). Note that you need to place the mesh at correct path or modify the problem file so that path to the mesh is correct.

**Comment by dlorod55** [comment]
Just to confirm what would be the ideal way to install turtleFSI on windows

**Comment by jorgensd** [comment]
> Just to confirm what would be the ideal way to install turtleFSI on windows

Using docker, as petsc, the LA backend of dolfin and turtleFSI is not easily installed on Windows

**Comment by dlorod55** [comment]
so whats the best way to use turtleFSI because im struggling lol

**Comment by keiyamamo** [comment]
As @jorgensd answered, docker is good. For further questions, please specify the exact problem you have.

**Comment by jorgensd** [comment]
> As in general if you were going to buy a laptop or pc to just run turtleFSI what and how would u do it. Like the best case scenario.

If you can buy a new laptop, I would either: 
1. Familiarize yourself with how docker works
2. Familiarize yourself with how subsystem for Linux (WSL2) works on Windows 
3. Buy a Linux based system.

**Comment by dlorod55** [comment]
i put file in right place but still staying not found. do i have to do anything after placing it into to the right directory 
/

**Comment by keiyamamo** [comment]
No, you shouldn't need do anything for that. You can go to the folder where you have `mesh4.xdmf` and run `pwd` command and then replace the path to the mesh inside the problem file.

**Comment by dlorod55** [comment]
fenics@6b4451a874e7:~/local/turtleFSI$ pwd
/home/fenics/local/turtleFSI
fenics@6b4451a874e7:~/local/turtleFSI$ turtleFSI --problem MovingCylinder
{'A_ratio': 0.25,
 'D': 0.1,
 'F_r': 1.0,
 'Re': 500,
 'St': 0.228,
 'T': 5,
 'Um': 0.8,
 'atol': 1e-07,
 'bc_ids': [],
 'c_s': 0.0,
 'checkpoint_step': 500,
 'compiler_parameters': {'add_tabulate_tensor_timing': False,
                         'cache_dir': '',
                         'convert_exceptions_to_warnings': False,
                         'cpp_optimize': True,
                         'cpp_optimize_flags': '-O2',
                         'epsilon': 1e-14,
                         'error_control': False,
                         'external_include_dirs': '',
                         'external_includes': '',
                         'external_libraries': '',
                         'external_library_dirs': '',
                         'form_postfix': False,
                         'format': 'ufc',
                         'generate_dummy_tabulate_tensor': False,
                         'log_level': 25,
                         'log_prefix': '',
                         'max_signature_length': 0,
                         'no-evaluate_basis_derivatives': True,
                         'optimize': True,
                         'output_dir': '.',
                         'precision': None,
                         'quadrature_degree': 4,
                         'quadrature_rule': None,
                         'representation': 'auto',
                         'split': False},
 'counter': 0,
 'd_deg': 1,
 'ds_s_id': None,
 'dt': 0.000125,
 'dx_f_id': 1,
 'dx_s_id': 2,
 'extrapolation': 'laplace',
 'extrapolation_sub_type': 'constant',
 'factor': 50.0,
 'fluid': 'fluid',
 'fluid_properties': [],
 'folder': 'results_moving_cylinder',
 'gravity': None,
 'k_s': 0.0,
 'killtime': None,
 'lambda_s': 450000.0,
 'linear_solver': 'mumps',
 'lmbda': 1.0,
 'loglevel': 20,
 'material_model': 'StVenantKirchoff',
 'max_it': 50,
 'mu_f': 0.2,
 'mu_s': 50000.0,
 'nu_s': 0.45,
 'p_deg': 1,
 'problem': 'MovingCylinder',
 'recompute': 25,
 'recompute_tstep': 100,
 'restart_folder': None,
 'rho_f': 1000,
 'rho_s': 1000.0,
 'robin_bc': False,
 'rtol': 1e-07,
 'save_deg': 1,
 'save_step': 100,
 'solid': 'no_solid',
 'solid_properties': [],
 'solver': 'newtonsolver',
 'sub_folder': None,
 't': 0,
 'theta': 0.500125,
 'u_inf': 1.0,
 'v_deg': 1,
 'verbose': True}
Traceback (most recent call last):
  File "/usr/local/bin/turtleFSI", line 11, in <module>
    load_entry_point('turtleFSI', 'console_scripts', 'turtleFSI')()
  File "/home/fenics/local/turtleFSI/turtleFSI/run_turtle.py", line 18, in main
    from turtleFSI import monolithic
  File "/home/fenics/local/turtleFSI/turtleFSI/monolithic.py", line 63, in <module>
    mesh, domains, boundaries = get_mesh_domain_and_boundaries(**vars())
  File "/home/fenics/local/turtleFSI/turtleFSI/problems/MovingCylinder.py", line 81, in get_mesh_domain_and_boundaries  
    infile.read(mesh)
RuntimeError:

*** -------------------------------------------------------------------------
*** DOLFIN encountered an error. If you are not able to resolve this issue
*** using the information listed below, you can ask for help at
***
***     fenics-support@googlegroups.com
***
*** Remember to include the error message listed below and, if possible,
*** include a *minimal* running example to reproduce the error.
***
*** -------------------------------------------------------------------------
*** Error:   Unable to open XDMF file.
*** Reason:  XDMF file "/home/fenics/local/turtleFSI/mesh/MovingCylinder/mesh4.xdmf" does not exist.
*** Where:   This error was encountered inside XDMFFile.cpp.
*** Process: 0
***
*** DOLFIN version: 2019.1.0
*** Git changeset:  74d7efe1e84d65e9433fd96c50f1d278fa3e3f3f
*** -------------------------------------------------------------------------

fenics@6b4451a874e7:~/local/turtleFSI$

**Comment by keiyamamo** [comment]
What's the result of pwd inside the folder mesh? What if you run the turtleFSI command where there's folder mesh and monolithic.py?

**Comment by dlorod55** [comment]
Hi, rather than doing a moving cylinder my airflow around a circle then an ellipse then an aerofoil. I'm confused how to start thats why i tried moving cylinder to see how that workeed.

**Comment by keiyamamo** [comment]
I’m not sure what you’re asking here and don’t have time to guide you step by step for all the details.

**Comment by keiyamamo** [comment]
Closing for now. Feel free to reopen if you have more questions @dlorod55
